// AUTH ACTION TYPES
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const FB_LOGIN_USER_FAIL = 'FB_LOGIN_USER_FAIL';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOADING_AUTH_USER = 'LOADING_AUTH_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export const LOADING_USER_EMAIL_SIGNUP = 'LOADING_USER_EMAIL_SIGNUP';
// USER LOGIN WITH EMAIL AND PASSWORD
export const LOGIN_USER_FAIL_WRONG_PASSWORD = 'LOGIN_USER_FAIL_WRONG_PASSWORD';
export const LOGIN_USER_FAIL_NO_USER = 'LOGIN_USER_FAIL_NO_USER';
export const LOGIN_USER_FAIL_INVALID_EMAIL = 'LOGIN_USER_FAIL_INVALID_EMAIL';
export const LOGIN_USER_FAIL_USER_DISABLED = 'LOGIN_USER_FAIL_USER_DISABLED';

// FEED ACTIONS
export const GET_RECD_ITEMS_SUCCESS = 'GET_RECD_ITEMS_SUCCESS';
export const GET_RECD_ITEMS_FAILURE = 'GET_RECD_ITEMS_FAILURE';
export const GET_RECD_ITEMS_LOADING = 'GET_RECD_ITEMS_LOADING';

// RECD MODAL ACTIONS
export const GET_SPOTIFY_ACCESS_TOKEN_SUCCESS = 'GET_SPOTIFY_ACCESS_TOKEN_SUCCESS';
export const GET_SPOTIFY_ACCESS_TOKEN_FAILURE = 'GET_SPOTIFY_ACCESS_TOKEN_FAILURE';
export const GET_SPOTIFY_TRACKS_SUCCESS = 'GET_SPOTIFY_TRACKS_SUCCESS';
export const GET_SPOTIFY_TRACKS_FAILURE = 'GET_SPOTIFY_TRACKS_FAILURE';
export const CLEAR_SEARCH_TRACK_ITEMS = 'CLEAR_SEARCH_TRACK_ITEMS';
export const RECD_SENT_SUCCESS = 'RECD_SENT_SUCCESS';
export const RECD_SENT_FAILURE = 'RECD_SENT_FAILURE';
export const RECD_SENT_LOADING = 'RECD_SENT_LOADING';
export const RESET_STATE = 'RESET_STATE';
