// AUTH ACTION TYPES
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOADING_AUTH_USER = 'LOADING_AUTH_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

// FEED ACTIONS
export const SHOW_RECD_MODAL = 'SHOW_RECD_MODAL';
export const HIDE_RECD_MODAL = 'HIDE_RECD_MODAL';

// RECD MODAL ACTIONS
export const GET_SPOTIFY_ACCESS_TOKEN_SUCCESS = 'GET_SPOTIFY_ACCESS_TOKEN_SUCCESS';
export const GET_SPOTIFY_ACCESS_TOKEN_FAILURE = 'GET_SPOTIFY_ACCESS_TOKEN_FAILURE';
export const GET_SPOTIFY_TRACKS_SUCCESS = 'GET_SPOTIFY_TRACKS_SUCCESS';
export const GET_SPOTIFY_TRACKS_FAILURE = 'GET_SPOTIFY_TRACKS_FAILURE';
export const CLEAR_SEARCH_TRACK_ITEMS = 'CLEAR_SEARCH_TRACK_ITEMS';
